name: twitter bot

on: 

  push:

    branches:
      - secrets-temp

jobs:

  build:
  
    name: Build
    
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
      - name: setting API
        uses: actions/setup-python@v2
        with:
        # Semantic version range syntax or exact version of a Python version
          python-version: '3.6' 
      
      - name: twitter bot

        shell: bash 
        run: | 
          pip install -r requirements.txt
          python ./twitterbot.py
        env:
            
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
        
        
        
