name: twitter bot
on: 
  push:
    branches:
      - main

jobs:
  build:  
    name: Build    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8
        with: 
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: hinglish-nlp
          heroku_email: radhika.sethi0312@gmail.com
        env:
          hD_ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          HD_ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
          HD_CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          HD_CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}  
        
        
